OpenRTM_aist/examples/Slider_and_Motor/slider.py
OpenRTM_aist/examples/TkJoyStick/tkjoystick.py
OpenRTM_aist/examples/TkLRFViewer/TkLRFViewer.py

close #13 
Link to #13
- Tkinterのデフォルトフォントを、下記3ファイルとも 'system 9' とした
- TkJoyStick/tkjoystick.py
- デフォルトフォント指定だけでは画面右半分の文字しか表示されなかったため、左半分は個別にフォントを指定している
- Slider_and_Motor/slider.py
- TkLRFViewer/TkLRFViewer.py
- 修正動作をFedora29とUbuntu16.04で確認（上図参照）

[master]Default font of Tk has been set. #13

---

OpenRTM_aist/ByteDataStreamBase.py
OpenRTM_aist/CORBA_CdrMemoryStream.py
OpenRTM_aist/ConnectorListener.py
OpenRTM_aist/FactoryInit.py
OpenRTM_aist/InPortPullConnector.py
OpenRTM_aist/InPortPushConnector.py
OpenRTM_aist/OutPortPullConnector.py
OpenRTM_aist/OutPortPushConnector.py
OpenRTM_aist/__init__.py

#21 
シリアライザの基底クラスとして**ByteDataStreamBase**クラスを定義した。
シリアライザは**ByteDataStreamBase**クラスを継承して**init**関数、**isLittleEndian**関数、**serialize**関数、**deserialize**関数を実装する必要がある。
以下の実装例を示す。
```CPP
#!/usr/bin/env python
import OpenRTM_aist
import RTC
class testSerializer(OpenRTM_aist.ByteDataStreamBase):
def __init__(self):
self._endian = None
def __del__(self):
pass
def init(self, prop):
pass
def isLittleEndian(self, little_endian):
pass
def serialize(self, data):
if data._NP_RepositoryId == RTC.TimedLong._NP_RepositoryId:
return OpenRTM_aist.ByteDataStreamBase.SERIALIZE_OK, ""
else:
return OpenRTM_aist.ByteDataStreamBase.SERIALIZE_ERROR, ""
def deserialize(self, cdr, data_type):
if data_type._NP_RepositoryId == RTC.TimedLong._NP_RepositoryId:
data_type.data = 444
return …
```

シリアライザ生成ファクトリの実装 #21

---

MANIFEST.in
packages/rpm/openrtm-aist_py3.spec.in
packages/rpm/rpm_build.sh

close #12 
Link to #12
- シバンの書き換えは、*.pyファイルだけでなく、/usr/bin下にインストールするrtcd_pythonとrtcprof_pythonも対象にする
- 当初、シバンの書き換えは「env python」→「env python3」としていた。
処理の途中段階で、rpm/SOURCES/に出力するものは「#!/usr/bin/env python3」と
なっているのに、パーミッションで実行権限が付いている/usr/bin下にインストールするファイルは、最終的に「#!/usr/bin/python2」と書き換わっていると判明。
- 「python2」となる原因
- specファイルで使っているマクロ%{__python}、%{python_sitelib} はpython2用だから
- python3の場合は、%{__python3}、%{python3_sitelib}マクロを使用する。このマクロ使用のため、python3-develのインストールが必要で、specファイル内も「BuildRequires: python3-devel」の定義が必要。
- 対応
- 従来の「openrtm-aist.spec.in」はpython2用として変更せず
- python3用は新たに「openrtm-aist_py3.spec.in」を定義し、rpm_build.sh内で、Fedoraバージョンが29以上はpython3用を使うようにした
- 自動でシバンの「env」が除かれる件
- 下記リンクのFedoraドキュメントによると、envは使ってはいけないとのこと　
「/usr/bin/python (as well as /usr/bin/env python and similar) MUST NOT be used in …

[master] Shebang rewriting when creating rpm package. #12

---

OpenRTM_aist/InPortCorbaCdrConsumer.py
OpenRTM_aist/InPortDSConsumer.py
OpenRTM_aist/InPortSHMConsumer.py
OpenRTM_aist/OutPortCorbaCdrConsumer.py
OpenRTM_aist/OutPortDSConsumer.py
OpenRTM_aist/OutPortSHMConsumer.py

#38 
そもそもCorbaConsumerのsetObjectで_narrow関数を呼ぶため、インターフェース型を設定していればput、getでいちいち_narrow関数を呼ぶ必要は無かったため修正した。

put、get関数で毎回_narrow関数を呼ばないようにする

---

OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py

ComponentObserverにC++版の以下のバグと同様の問題があったため修正した。
https://github.com/OpenRTM/OpenRTM-aist/pull/183

ComponentObserverのバグ修正(1.2)

---

OpenRTM_aist/RTObject.py

1. ECを2回stopしたことによるエラー
2. RTCが非アクティブ、エラー状態でdeactivateすることによるエラー
1、2の修正を行った。
1の修正により外部ECを停止する処理も無くなった。
2の修正によりアクティブ状態の時はdeactivate、エラー状態の時はresetするようになった。

RTC終了時にログにエラーが出力される問題の修正

---

OpenRTM_aist/Manager.py

RTCをomniINSPOAでactivate_objectした場合に、RTObjectとManagerで2回deactivate_objectを実行してしまう。
Mangerのdeactivate_objectに関する処理は必要ないため削除した。

RTCのomniINSPOAでのdeactivate_objectを2回実行しないように修正

---

OpenRTM_aist/Properties.py

#50 
Propertiesで値が設定されていない場合にはvalueにNoneを設定して空白文字列と明確に区別するようにした。

rtc.confで値が空白の場合に反映されない問題の修正

---

OpenRTM_aist/ModuleManager.py

Pythonファイルを動的にロードする際に、文字コードがshift_jis以外だとエラーになる。
Python3のみ発生する。
Pythonファイルに事前にInit関数があるかを確認する部分で問題が発生していたため、文字コードを判別する処理を追加した。

モジュールロード時に開くファイルの文字コードによってエラーが発生する問題の修正

---

OpenRTM_aist/InPortBase.py
OpenRTM_aist/OutPortBase.py
OpenRTM_aist/RTM_IDL/BasicDataType.idl
OpenRTM_aist/RTM_IDL/ExtendedDataTypes.idl
OpenRTM_aist/RTM_IDL/InterfaceDataTypes.idl
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceInPort.py
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceMessageInfo.py
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceOutPort.py
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceSerializer.py
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceTopicManager.py
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceTransport.py
OpenRTM_aist/ext/transport/OpenSplice/rtc.conf
OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
setup.py

データポートにDDS通信インターフェースを実装する。
一部ファイルがコミットできていなかったため、一旦draftに設定します。
- Fast-RTPs
- DDS for TAO
Pythonの実装がない。
- rticonnextdds-connector-py
サンプルではXMLファイルでデータ型を定義している。
IDLファイルで定義可能かは要調査。
- OpenSplice
IDLファイルでデータ型を定義しており、omnoORBと使用方法は近い。
ただし、どのIDLファイルがどのデータ型を定義しているのか知る必要があるため工夫が必要。
上記の理由によりOpenSpliceで実装。
Topic、Publisher、Subscriber初期化時にデータ型に関する情報が必要なため、コネクタプロファイルにデータ型名を格納するようにした。
- OpenSpliceInPort.py
Subscriber側の実装。OpenSpliceのReaderを生成し、コールバック関数を設定する。
- OpenSpliceOutPort.py
Publisher側の実装。OpenSpliceのWriterを生成し、put関数実行時にデータを書き込む。
- OpenSpliceTopicManager.py
DomainParticipant、publisher、subscriberの初期化などを定義。
DomainParticipantは一度しか初期化しないため、QOSの設定は最初に生成したコネクタのプロファイルが反映される。
- OpenSpliceSerializer.py
OpenSpliceのPythonラッパーライブラリにはCDRバイト列を書き込む関数などはない。
このため、一旦omniORBの変数からOpenSpliceの変数に値を移すようにしている。
- …

DDS通信機能の実装

---

OpenRTM_aist/RTObject.py

サービスポート接続時にaddPortConnectRetListenerなどで設定したコールバック関数が呼ばれない。
このためコンポーネントオブザーバーによる通知も行われず、RTSE上でポートが接続されていないように見える。
サービスポート接続時にもコールバック関数が呼ばれるようにした。

サービスポート接続時にコネクタのコールバック関数が呼ばれない問題の修正

---

OpenRTM_aist/CORBA_RTCUtil.py

CORBA_RTCUtilの以下の関数について、指定IDのECが取得できなかった場合にNoneに設定した変数から関数を呼び出そうとしてします。
- get_default_rate関数
- set_default_rate関数
- get_current_rate関数
- set_current_rate関数
指定IDのECが取得できなかった場合を判定してBAD_PARAMETERを返すようにした。

CORBA_RTCUtilのget_default_rate関数、set_default_rate関数、get_current_rate関数、set_current_rate関数でECが取得できなかった場合にBAD_PARAMETERを返すようにする

---

OpenRTM_aist/SharedMemory.py

同一プロセス内でインターフェース型をshared_memoryに設定してデータポートを接続すると、接続時にエラーが発生する。
以下のsetObject関数内で、CorbaConsumerの`_ptr`関数でオブジェクトを取得するが、同一プロセス内の場合はオブジェクトリファレンスではなく実体を返す。
```Python
def setObject(self, obj):
if OpenRTM_aist.CorbaConsumer.setObject(self, obj):
portshmem = self._ptr()
if portshmem:
self._shmem.setInterface(portshmem)
return True
return False
```
このあとCORBA.is_nilに`_ptr`関数で取得したオブジェクトを入力するとエラーになる。
このため、以下のようにまずオブジェクトリファレンスか実体かを判別するようにした。
```Python
def setInterface(self, sm):
if isinstance(sm, SharedMemory):
self._smInterface = sm
else:
if not CORBA.is_nil(sm):
self._smInterface = sm
```
if this request do not need to build and tests, delete the items …

同一プロセス内でインターフェース型shared_memoryでデータポートを接続するとエラーが発生する問題の修正

---

OpenRTM_aist/InPortBase.py
OpenRTM_aist/InPortConnector.py
OpenRTM_aist/InPortDuplexConnector.py
OpenRTM_aist/InPortPullConnector.py
OpenRTM_aist/OutPortBase.py
OpenRTM_aist/OutPortConnector.py
OpenRTM_aist/OutPortDuplexConnector.py
OpenRTM_aist/OutPortPushConnector.py

データポートのコネクタをdisconnectした際にInPortConsumer、OutPortConsumerの`unsubscribeInterface`関数が呼び出されない問題があるが、ソースコードを読んだ限り呼び出すような記述自体がないため仕様かバグかも不明。
ROSTransportなどはunsubscribeInterface関数が呼び出されないと異常終了する可能性があるため`unsubscribeInterface`関数が呼び出されるように変更した。
`unsubscribeInterface`関数の引数にコネクタプロファイルが必要のため、OutPortConnector、InPortConnectorに`unsubscribeInterface`関数を追加してInPortBase、OutPortBaseのunsubscribeInterfaces関数内で呼び出すようにした。

unsubscribeInterfaceが呼び出されない問題の修正

---

OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py

C++版の以下の変更と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/409

コンポーネントオブザーバーのタイマースレッドをonFinalizeで終了する処理に変更(1.2)

---

OpenRTM_aist/ext/fsm4rtc_observer/ComponentObserverConsumer.py
OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py

C++版と以下の点でコンポーネントオブザーバーの動作が違っている。
- タイマースレッドの周期はC++版ではコンストラクタで設定した値で固定。Python版は`heartbeat.enable`で設定した値に変更される。タイマースレッド動作中に周期を変更することは通常ないためC++版に合わせる必要がある。
- タイマースレッドの周期がC++版は0.1秒、Python版は1.0秒。
C++と同じ動作になるように修正した。

C++版とコンポーネントオブザーバーの動作が違うため修正

---

OpenRTM_aist/CORBA_RTCUtil.py

以下と同じ
https://github.com/OpenRTM/OpenRTM-aist/pull/428

already_connected関数に同一のポートを2個指定した場合にfalseを返すようにする

---

OpenRTM_aist/CSPMachine.py
OpenRTM_aist/InPortCSPConsumer.py
OpenRTM_aist/InPortCSPProvider.py
OpenRTM_aist/InPortDuplexConnector.py
OpenRTM_aist/OutPortCSPConsumer.py
OpenRTM_aist/OutPortCSPProvider.py
OpenRTM_aist/OutPortDuplexConnector.py
setup.py

#14
subprocess.getstatusoutputはPython3ではうまく動作しないようです。
getstatusoutput関数は[Python3のドキュメント](https://docs.python.org/ja/3/library/subprocess.html#legacy-shell-invocation-functions)で「レガシーなシェル呼び出し関数」と書かれているので、今後改善する可能性もなさそうです。
このためsubprocess.runを使う方法に変更しました。
また一部のファイルで文字コード、改行コードに誤りがありsetup.py実行時にエラーとなったため修正した。

Linux、Python3でビルドを実行するとエラーになる問題の修正

---

OpenRTM_aist/examples/ExtTrigger/Connector.py

ExtTriggerのConnector.py実行中に`Exception`と表示されてそれ以降はtickが実行できなくなる。
CorbaConsumerの_ptr関数内でManagerのインスタンスを取得していることが原因。
```
def _ptr(self, get_ref=False):
if get_ref:
return self._var
if self._sev is not None:
return self._sev
try:
mgr = OpenRTM_aist.Manager.instance()
self._sev = mgr._poa.reference_to_servant(self._var)
return self._sev
except:
return self._var
```
Managerを初期化していない場合、_ptr関数内で初めてManagerを初期化することになる。
この時1つもRTCが起動していないため、10秒後にManagerが自動終了してしまいExceptionが発生していた。
Connector.pyでManagerを初期化してからtick等を実行するようにした。
Managerが時間で自動的に終了する機能はトラブルを起こすことが多いためデフォルトでオフにした方がいいと思います。
if this request do not need to build and tests, delete the items and …

ExtTriggerのサンプルが正常に動作しない問題の修正

---

OpenRTM_aist/CSPEventPort.py
OpenRTM_aist/CSPInPort.py
OpenRTM_aist/CSPMachine.py
OpenRTM_aist/CSPManager.py
OpenRTM_aist/CSPOutPort.py
OpenRTM_aist/EventPort.py
OpenRTM_aist/InPortCSPConsumer.py
OpenRTM_aist/InPortCSPProvider.py
OpenRTM_aist/InPortDuplexConnector.py
OpenRTM_aist/OutPortCSPConsumer.py
OpenRTM_aist/OutPortCSPProvider.py
OpenRTM_aist/OutPortDuplexConnector.py
OpenRTM_aist/examples/CSPStaticFsmSample/Inputbutton.py
OpenRTM_aist/examples/CSPStaticFsmSample/Microwave.py
OpenRTM_aist/examples/StaticFsm/Inputbutton.py

CSPポートに関連する以下の問題を修正した。
- CSPポート関連のファイルの文字コードをUTF-8に統一した
- 外部選択を行うためのCSPManagerの設定をCSPポート初期化後にも再設定できるようにした。(違うポートを対象にした外部選択の実装のため)
- StaticFSM.MachineクラスとCSPManagerクラスを多重継承してCSPMachineクラスを定義していたが、これはCSPポートが複数回外部選択を行う場合に都合が悪いためCSPManagerクラスの継承はやめた。
- CSPEventPortでOutPortが送信待ち状態の時に受信処理を開始した際にコネクタコールバック関数が呼ばれない問題の修正。

CSPポートの不具合修正

---

OpenRTM_aist/examples/ConfigSample/ConfigSample.py

ConfigSample.pyの以下の部分でリストと数値を比較しているが、Python2ではリスト内の数値と比較してくれるがPython3ではエラーになる。
```Python
if self._int_param0 > 1000 and self._int_param0 < 1000000:
time.sleep(self._int_param0/1000000.0)
```
数値同士を比較するように修正した。

ConfigSample.pyがPython3で正常に動作しないバグの修正(1.2)

---

OpenRTM_aist/ext/fsm4rtc_observer/ComponentObserverConsumer.py
OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py

#76 の変更によりRTCをexitしたときにコンポーネントオブザーバーのタイマースレッドが停止するようになったが、`remove_service_profile`で削除した場合にタイマースレッドが停止しない。
コンポーネントオブザーバーの終了処理でもタイマースレッドを停止するようにした。

remove_service_profileでコンポーネントオブザーバーを削除した場合にタイマースレッドが停止しない問題の修正

---

OpenRTM_aist/ListenerHolder.py
OpenRTM_aist/Manager.py
OpenRTM_aist/ManagerActionListener.py

#98
#95 
- ManagerActionListenerクラス、ModuleActionListenerクラス、RtcLifecycleActionListenerクラス、NamingActionListenerクラス、LocalServiceActionListenerクラスを定義
- 戻り値を引数の変数に格納することで、引数ありListenerで値を変更する場合に引数の値も変更するようにした

ManagerActionListenerの基底クラス追加、引数ありListenerの修正

---

OpenRTM_aist/ManagerConfig.py

Windowsでrtc.confのパスをインストールされるrtc.confに設定していたが、これが原因で`C:\Python37\rtc.conf`を読み込んで誤動作を起こすなど問題があった。
rtc.confのパスを`%APPDATA%\OpenRTM-aist\rtc.conf`に変更した。ここには意図してrtc.confを配置しない限りは読み込まないため上記のようなトラブルは発生しないはず。

rtc.confのパスの修正

---

OpenRTM_aist/Timer.py

#132 でTimerの仕様を大幅に変更したが、Timerクラスがobject型を継承していないためPython2でエラーが出るようになった。
Python3ではobject型の継承は明示する必要がないためエラーは出ない。
Timerクラスがobject型を継承するようにした。

Timerクラスがobject型を継承していないためPython2でエラーが発生する問題の修正

---

OpenRTM_aist/ConnectorListener.py

ConnectorDataListenerクラスがobject型を継承していないため、Python2でissubclassの判定が正常に実行されない。
ConnectorDataListenerクラスがobject型を継承するようにした。

ConnectorDataListenerクラスがobject型を継承していないためPython2でエラーが発生する問題の修正

---

OpenRTM_aist/ConnectorListener.py
OpenRTM_aist/InPortDuplexConnector.py
OpenRTM_aist/InPortPullConnector.py
OpenRTM_aist/InPortPushConnector.py
OpenRTM_aist/OutPortDuplexConnector.py
OpenRTM_aist/OutPortPullConnector.py
OpenRTM_aist/OutPortPushConnector.py

InPortPushConnector等で指定のシリアライザが存在しなかった場合にNoneの変数を操作しようとする。
指定のシリアライザが存在しない場合はUNKNOWN_ERRORを返すように修正した。
ConnectorDataListenerではデシリアライズせずにバイト列のデータのままコールバック関数を実行する場合があるため、シリアライザが存在しない場合でも処理を続行するようにしている。

指定のシリアライザが生成できなかった場合に適切に処理する

---

OpenRTM_aist/InPort.py
OpenRTM_aist/InPortBase.py
OpenRTM_aist/InPortPullConnector.py
OpenRTM_aist/InPortPushConnector.py

…s changed.
InPortPullConnector、InPortPushConnectorのread関数内でデシリアライズを実行するが、デシリアライズ後のデータ型の指定方法は以下の2つがある。
- read関数の引数で指定する
- InPortConnectorのsetDataType関数で設定する
しかしInPortPullConnectorではsetDataType関数が呼ばれておらず、InPortPushConnectorのread関数では引数で指定した型でデシリアライズを実行しないようになっており、方法が統一されていない。
デシリアライズ後のデータ型の指定は以下の方法に統一した。
- ポートにデータ型設定されている場合は、InPortPullConnector、InPortPushConnectorのどちらでもsetDataType関数で設定する
- read関数の引数でデータ型を指定した場合は、setDataType関数で指定した型ではなく引数のデータ型にデシリアライズする

デシリアライズ後のデータ型の指定方法の見直し

---

OpenRTM_aist/BufferStatus.py
OpenRTM_aist/ComponentActionListener.py
OpenRTM_aist/ConfigurationListener.py
OpenRTM_aist/ConnectorListener.py
OpenRTM_aist/DataPortStatus.py
OpenRTM_aist/FsmActionListener.py
OpenRTM_aist/PortConnectListener.py

BufferStatus.py等にIDを文字列に変換する`toString`関数が定義してあるが、以下の問題がある。
- `type`等、予約語を変数名にしている箇所が多数ある
- `PRE_COMPONENT_ACTION_LISTENER_NUM`等のIDの数を表す定数を定義して入力したIDと比較しているが、文字列のリストの長さと比較(`if status < len(typeString):`)すれば他のtoString関数と同じ記述になるため簡単になる。
- `type`を変数名に称している箇所を修正
- 文字列のリストに`***_NUM`というIDの数を定義した変数名が含まれている箇所があるが、無意味のため削除
- 入力した番号と文字列のリストの長さを比較する方法に変更
- `PortConnectListenerType`が間違っていたため修正

IDを文字列に変換するtoString関数の修正

---

OpenRTM_aist/SystemLogger.py

FluentLoggerで以下のエラーが発生することがある。
```
2020-02-04 19:10:02.000000000 +0900 test.simpleio: {"level":"CRITICAL","message":"Can't output to log","traceback":"Traceback (most recent call last):\n  File \"C:\\Python37\\lib\\site-packages\\fluent_logger-0.9.3-py3.7.egg\\fluent\\sender.py\", line 90, in emit_with_time\n    bytes_ = self._make_packet(label, timestamp, data)\n  File \"C:\\Python37\\lib\\site-packages\\fluent_logger-0.9.3-py3.7.egg\\fluent\\sender.py\", line 133, in _make_packet\n    return msgpack.packb(packet, **self.msgpack_kwargs)\n  File \"C:\\Python37\\lib\\site-packages\\msgpack-0.6.1-py3.7-win-amd64.egg\\msgpack\\__init__.py\", line 46, in packb\n    return Packer(**kwargs).pack(o)\n  File \"msgpack\\_packer.pyx\", line 282, in msgpack._cmsgpack.Packer.pack\n  File …
```

FluentLoggerに文字列ではなくProperties型を入力してエラーになる問題の修正

---

OpenRTM_aist/utils/rtcd/rtcd_python3
OpenRTM_aist/utils/rtcprof/rtcprof_python3
packages/deb/debian/changelog
packages/deb/debian/control
packages/deb/debian/rules
packages/deb/dpkg_build.sh
setup.py

Link to #176 
- setup.pyを実行するコマンドをpython3と指定した
- debファイルのバージョン番号を 1.2.1-1 とした
- debパッケージビルド時に依存しているomniORBpyを、python3-omniorb と指定
- debパッケージのインストール先は、Python2.7用 をインストールされている環境とバッティングしないようにした
- /usr/binにインストールするコマンド名は、rtcd_python3、rtcprof_python3
- exampleとdocのインストール先はpython3ディレクトリ下
/usr/share/openrtm-1.2/components/python3
/usr/share/openrtm-1.2/doc/python3
- OpenRTM-aist-Python本体のインストール先
/usr/lib/python3/dist-packages/OpenRTM_aist
- ビルド時に python3.6/distutils/command/install_lib.py でエラーが発生したことへの対応
- setuplpyのinstall_core_libとinstall_core_script関数内でfinalizeの呼び出しが抜けていたので追加
- Ubuntu18.04のDocker環境へ生成したOpenRTM-aist-Pythonをインストールしての動作確認
- サンプルRTC ConsoleIn.pyとConsoleOut.pyの接続動作 OK（rtshell利用）
- pythonは3のみで、2.7はインストールされていない
```
bash: python: command not found
Python 3.6.9
```
- …

Python3用debパッケージを生成できるように整備(1.2)

---

OpenRTM_aist/examples/TkLRFViewer/TkLRFViewer.py

[UrgRTCComp.zip](https://github.com/OpenRTM/OpenRTM-aist-Python/files/4254680/UrgRTCComp.zip)
issue #175 
デフォルトスケールで、表示スケールを1 dot/mから100 dot/m (dot/cm)に変更、また、Thresholdnの値の実際の単位が、これまでm単位だったのをcm単位の値として扱うように変更。
インタプリタ用のファイルなので、ビルドは特にせず、直接実行しているのみです。
実際にHokyoURG-04Xをつかい、Suga-sanの2014/JanリリースのRTCを用いて動作検証。RTCの入手元は：https://github.com/sugarsweetrobotics/UrgRTC
コンパイルした結果のバイナリは下記に添付
[UrgRTCComp.zip](https://github.com/OpenRTM/OpenRTM-aist-Python/files/4254684/UrgRTCComp.zip)

表示スケールを1 dot/mから100 dot/m (1 dot/cm)に変更

---

OpenRTM_aist/Process.py

`get_loadable_modules()`等でロード可能なモジュールを取得しようとすると以下のエラーメッセージが表示される。
```
popen faild
```
Python3からは`subprocess`の`communicate`関数の戻り値がstr型からbytes型に仕様変更されているため、str型に変換して返すように修正した。
この修正でPython2でエラーが出るようになったが、masterブランチではPython2はサポートしないため場合分けなどは行わない。

ローダブルモジュールの取得が失敗するエラーの修正

---

OpenRTM_aist/utils/rtcprof/rtcprof.py

再現はできていないが、rtcprof.py実行時に以下のエラーが発生するらしい。
```
C:\Python37>rtcd_python.exe -d -f rtc.conf
Traceback (most recent call last):
File "C:\Python37\rtcprof.py", line 112, in <module>
main()
File "C:\Python37\rtcprof.py", line 65, in main
if f.read().find(comp_spec_name) == -1:
UnicodeDecodeError: 'cp932' codec can't decode byte 0x90 in position 2: illegal multibyte sequence
```
おそらく読み込むファイルの文字コード次第で発生するエラーだと考えられるため、文字コードを判別してから読み込むように修正した。

rtcprof実行時に発生するエラーの修正

---

OpenRTM_aist/ByteDataStreamBase.py
OpenRTM_aist/CORBA_CdrMemoryStream.py
OpenRTM_aist/ConnectorListener.py
OpenRTM_aist/InPort.py
OpenRTM_aist/InPortBase.py
OpenRTM_aist/InPortDuplexConnector.py
OpenRTM_aist/InPortPullConnector.py
OpenRTM_aist/InPortPushConnector.py
OpenRTM_aist/OutPort.py
OpenRTM_aist/OutPortBase.py
OpenRTM_aist/OutPortConnector.py
OpenRTM_aist/OutPortDuplexConnector.py
OpenRTM_aist/OutPortPullConnector.py
OpenRTM_aist/OutPortPushConnector.py
OpenRTM_aist/examples/Serializer/ShortToDoubleSerializer.py
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceSerializer.py
OpenRTM_aist/ext/transport/ROS2Transport/ROS2Serializer.py
OpenRTM_aist/ext/transport/ROSTransport/ROSSerializer.py

現状の実装ではデータ型ごとに使用できるシリアライザが区別できず、例えばTimedFloat型のデータポートで`ros2:sensor_msgs/Image`型が選択できたりする。
C++と同様にシリアライザ生成ファクトリを操作する以下の関数を実装した。
- `addSerializer`：シリアライザの登録(データ型指定)
- `removeSerializer`：シリアライザの登録解除(データ型指定)
- `createSerializer`：シリアライザの生成
- `getSerializerList`：使用可能なシリアライザの一覧取得
ファクトリはデータ型ごとに用意するようにした。

シリアライザ生成ファクトリの仕様変更

---

OpenRTM_aist/ext/transport/ROS2Transport/ROS2Serializer.py

ROS2Transportの基本データ型を変換するシリアライザでは、以下のようにserialize関数内でROS2メッセージ型のフィールド型名からRTMのデータを適切な型に変換する処理を行っているが、フィールド型名がROS2のcrystalとdashingで異なっている。
```
def serialize(self, data):
msg = message_type()
field_type = msg.get_fields_and_field_types()["data"]
if field_type == "int8" or field_type == "int16" or field_type == "int32" or field_type == "int64":
msg.data = int(data.data)
elif field_type == "uint8" or field_type == "uint16" or field_type == "uint32" or field_type == "uint64":
msg.data = int(data.data)
elif field_type == "float32" or field_type == "float64":
msg.data = float(data.data)
elif field_type == "int8[]" or field_type == "int16[]" or field_type == "int32[]" or field_type == "int64[]":
msg.data = list(map(int, data.data))
elif field_type == "uint8[]" or field_type == "uint16[]" or …
```

ROS2Transportのデータの変換で発生するエラーの修正

---

OpenRTM_aist/ByteDataStreamBase.py
OpenRTM_aist/CORBA_CdrMemoryStream.py
OpenRTM_aist/ConnectorListener.py
OpenRTM_aist/InPort.py
OpenRTM_aist/InPortBase.py
OpenRTM_aist/InPortDuplexConnector.py
OpenRTM_aist/InPortPullConnector.py
OpenRTM_aist/InPortPushConnector.py
OpenRTM_aist/OutPort.py
OpenRTM_aist/OutPortBase.py
OpenRTM_aist/OutPortConnector.py
OpenRTM_aist/OutPortDuplexConnector.py
OpenRTM_aist/OutPortPullConnector.py
OpenRTM_aist/OutPortPushConnector.py
OpenRTM_aist/examples/Serializer/ShortToDoubleSerializer.py
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceSerializer.py
OpenRTM_aist/ext/transport/ROS2Transport/ROS2InPort.py
OpenRTM_aist/ext/transport/ROS2Transport/ROS2OutPort.py
OpenRTM_aist/ext/transport/ROS2Transport/ROS2Serializer.py
OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
OpenRTM_aist/ext/transport/ROSTransport/ROSSerializer.py
OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py

`RTC::CameraImage`->`sensor_msgs/Image`への変換時に画像データを格納した変数をそのままコピーしていたが、`sensor_msgs/Image`型では画像データをarray型で持っており`RTC::CameraImage`型にコピーするためにはbyte型への変換が必要だったため修正した。
また`std_msgs/Int8MultiArray`->`RTC::TimedOctetSeq`もbyte型への変換が必要だったため修正した。

ROS2TransportのImage型、Int8MultiArray型の変換時の不具合修正

---

OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py

以下のsocket終了処理がWindowsとLinuxで動作が異なる。
https://github.com/OpenRTM/OpenRTM-aist-Python/blob/dfadd5c3fc0488bf69d1aab86a31a5173ab9c917/OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py#L329-L330
Windowsの場合はshutdown関数で以下の例外が発生する。
ただし、shutdown関数が無くてもclose関数のみで正常終了する。
```
OSError: [WinError 10057] ソケットが接続されていないか、sendto 呼び出しを使ってデータグラム ソケットで送信するときにアドレスが指定されていないため、データの送受信を要求することは禁じられています。
```
Linuxの場合は例外は発生しないが、shutdown関数がない場合はaccept関数でブロックされたままになる。
pythonのsocketにはソケットが接続されていないかどうか確認する関数はないため、shutdown関数のみtry～exceptで例外処理を行うように変更した。

ROSTransportの終了処理を修正

---

OpenRTM_aist/ConfigAdmin.py
OpenRTM_aist/ConnectorListener.py
OpenRTM_aist/InPortBase.py
OpenRTM_aist/OutPortBase.py

本来は`=!`や`==`で比較する箇所を`is not`や`is`で比較しているコードがあるため警告が発生する。
警告の発生した箇所を修正した。

構文の間違いで発生する警告の修正(1.2)

---

OpenRTM_aist/PeriodicExecutionContext.py

Clock rewind causes hung and fixed it.
#208
The default execution context has a bug that causes RTC to hang when rewinding the system clock.
If the system clock rewind detected during RTC's logic execution, skip the sleep in EC.

Clock rewind hung bug #208 fixed (master)

---

OpenRTM_aist/PeriodicExecutionContext.py

Clock rewind causes hung and fixed it.
#208
The default execution context has a bug that causes RTC to hang when rewinding the system clock.
If the system clock rewind detected during RTC's logic execution, skip the sleep in EC.

Clock rewind hung bug #208 fixed (RELENG_1_2)

---

OpenRTM_aist/PeriodicExecutionContext.py

Link to #211 
- b3ef316 の修正でファイルの文字コードがeucからutf-8に変更されたため、シバンの設定と一致せずエラーとなっていた
- masterブランチは文字コードをutf-8に変更済なので、該当ファイルもシバンをutf-8に変更する修正を行った
- 修正後、Ubuntu20.04, omniORB4.2.4 の環境で、ConsoleIn.py/ConsoleOut.py の接続動作を確認した

PeriodicExecutionContext.pyの修正(1.2)

---

OpenRTM_aist/Manager.py
OpenRTM_aist/version.py

- OpenRTM-aist と同じ内容になるように更新した  OpenRTM/OpenRTM-aist#877
- 動作確認したところ、ログファイルに出力されるバージョン番号が1.2.1だったので、version.pyも修正した
- OpenRTM-aist-Python 1.2.2をインストールしている環境で、修正ファイルのみ差し替えてログファイル内容を確認した
```
2020-06-26 10:44:27,323 file.manager INFO 1.2.2
2020-06-26 10:44:27,323 file.manager INFO Copyright (C) 2003-2020, Noriaki Ando and OpenRTM development team,
2020-06-26 10:44:27,323 file.manager INFO   Intelligent Systems Research Institute, AIST,
2020-06-26 10:44:27,323 file.manager INFO Copyright (C) 2020, Noriaki Ando and OpenRTM development team,
2020-06-26 10:44:27,323 file.manager INFO   Industrial Cyber-Physical Research Center, AIST,
2020-06-26 10:44:27,323 file.manager INFO   All right reserved.
```

Copyright message in log-header updated. (1.2)

---

OpenRTM_aist/ManagerServant.py
OpenRTM_aist/ModuleManager.py

get_loadable_modules関数でローダブルモジュールのリストを取得すると以下のような情報が得られるが、`language`は`rtcprof`の言語ではなくRTCの仕様(ソースコードの`***_spec`で定義)から取得するため、例えば`rtcprof_python3`でプロファイル取得を行ったとしても`language`は`Python3`ではなく`Python`に設定されてしまう。
```
- implementation_id: ConsoleOut
- type_name: ConsoleOut
- description: Console output component
- version: 1.0
- vendor: Shinji Kurihara
- category: example
- activity_type: DataFlowComponent
- max_instance: 10
- language: Python
- lang_type: script
- module_file_name: ConsoleOut.py
- module_file_path: C:/Program Files/OpenRTM-aist/1.2.1/Components/Python/Examples/SimpleIO/ConsoleOut.py
```
`language`の要素を使用した`rtcprof`の言語名で上書きするようにした。

get_loadable_modulesで取得したロード可能モジュールの言語名をrtcprofの言語に設定する

---

OpenRTM_aist/PeriodicExecutionContext.py

Link to #222 
- PeriodicExecutionContext.py の文字コードをEUCに変更し、シバンも euc-jp とした
- RELENG1_2 ブランチのDoxyfile_jp.in にて「INPUT_ENCODING = euc-jp」と定義しており、他のソースもEUCのため同様に変更した
- なお、masterブランチソースは文字コードをUTF-8に変更しているため、この修正は反映させない
- この修正により、docのdebパッケージを生成できるようになった

doxygenビルド向けにPeriodicExecutionContext.pyの文字コードをEUCに変更(1.2)

---

OpenRTM_aist/examples/ExtTrigger/Connector.py
OpenRTM_aist/examples/ExtTrigger/run.py
OpenRTM_aist/examples/SimpleIO/Connector.py
OpenRTM_aist/examples/SimpleIO/run.py
OpenRTM_aist/examples/SimpleService/Connector.py
OpenRTM_aist/examples/SimpleService/run.py
OpenRTM_aist/examples/Slider_and_Motor/Connector.py
OpenRTM_aist/examples/Slider_and_Motor/run.py

- サンプルコンポーネントのrun.pyを実行するとRTC起動前に接続処理を実行してエラーになる
- run.pyでのネームサーバーの起動処理でkill-rtm-naming.batが見つからないというエラーが発生する。これは`C:\Program Files\OpenRTM-aist\x.y.z\bin`にパスが通っていないため。
- RTCが見つかるまでポーリングするように修正
- 一旦`%RTM_ROOT%\bin`に移動してrtm-naming.batを実行するように修正

サンプルコンポーネントのrun.pyが正常に動作するように修正

---

packages/deb/debian/control

Link to #231
openrtm-aist-python3 の依存パッケージにpython3-omniorbを追加した
```
$ less openrtm-aist-python3_1.2.2-0_amd64.deb
:
Depends: python3-omniorb, omniorb-nameserver
```

openrtm-aist-pythonの依存パッケージにpython3-omniorbを追加した(1.2)

---

OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceTransport.py
OpenRTM_aist/ext/transport/ROS2Transport/ROS2Transport.py
OpenRTM_aist/ext/transport/ROSTransport/ROSTransport.py

ROSTransport.py等でマネージャのリスナを追加しているが、OpenRTM_aist.ManagerActionListenerを継承せずにクラスを定義している。
OpenRTM_aist.ManagerActionListenerを継承するようにする。動作は変化しない。

マネージャのリスナを設定するときにOpenRTM_aist.ManagerActionListenerを継承するようにする

---

OpenRTM_aist/Manager.py
OpenRTM_aist/StringUtil.py

以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/issues/880

parseArg関数の実装

---

OpenRTM_aist/ConfigAdmin.py

rtshellで以下の問題が発生する。
- https://github.com/gbiggs/rtshell/issues/24
コンフィギュレーションパラメータ、コンフィギュレーションセットが設定されていないRTC(ConsoleIn等)については、コンフィギュレーションセットは1つもない状態になる。
RTSystemEditor等でコンフィギュレーションパラメータを取得する際にgetActiveConfigurationSetを呼び出しており、getActiveConfigurationSetを呼ぶとdefaultコンフィギュレーションセットが追加される。
getActiveConfigurationSetが呼ばれた段階でdefaultコンフィギュレーションセットが追加されるという動作は分かりづらいだけなので、ConfigAdmin初期化時に追加するように変更した。

defaultのコンフィギュレーションセットはRTC生成時に追加するようにする

---

OpenRTM_aist/docs/Doxyfile_jp.in
packages/deb/debian/changelog
packages/deb/debian/control
packages/deb/debian/rules
packages/deb/dpkg_build.sh
setup.py

Close #245 
Link to #245 
- setup.py sdist でソースパッケージ生成に関する修正
- FluentLoggerプラグイン名前変更に対応 (setup.py)
- Doxygenドキュメントビルド時のエラー対応
- Doxyfile_jp.inのINPUT_ENCODINGをeuc-jpからUTF-8へ変更
- Python3対応debパッケージ生成に関する修正
- setup.pyの修正
- unix向けスクリプト名の変更 -> rtcd_python3、rtcprof_python3
- example、docのディレクトリ変更 -> /components/python3、/doc/python3
- python3.x/distutilsでのエラー対応で、install_core_libとinstall_core_script関数内でのfinalize呼び出し追加
- packages/deb の修正
- debパッケージ作成を確認
```
openrtm-aist-python3-doc_2.0.0-0_all.deb  openrtm-aist-python3-example_2.0.0-0_amd64.deb  
openrtm-aist-python3_2.0.0-0_amd64.deb
```
- 上記debパッケージでインストールし、RTSE上でサンプルRTCのConsoleIn/ConsoleOutの接続動作OKを確認
- OpenRTM-aistはインストールしていないため、ネームサーバは下記で起動した
```
$ python3 /usr/lib/python3/dist-packages/OpenRTM_aist/utils/rtm-naming/rtm-naming.py
```

Python3環境でdebパッケージ生成時の不具合修正

---

OpenRTM_aist/ext/transport/ROS2Transport/ROS2TopicManager.py

#248 の修正でROS2 foxyに対応したが、ROS2 dashingでエラーが発生し接続できなくなった。
ROS2 dashingとfoxyで以下のクラス名が変わっているため、どちらにも対応できるようにした。
|dashing|foxy|
|---|---|
|rclpy.qos.QoSHistoryPolicy|rclpy.qos.HistoryPolicy|
|rclpy.qos.QoSDuration|rclpy.qos.Duration|
|rclpy.qos.QoSReliabilityPolicy|rclpy.qos.ReliabilityPolicy|
|rclpy.qos.QoSDurabilityPolicy|rclpy.qos.DurabilityPolicy|
|rclpy.qos.QoSLivelinessPolicy|rclpy.qos.LivelinessPolicy|

ROS2TransportがROS2 dashingで実行時にエラーになる問題の修正

---

OpenRTM_aist/ModuleManager.py

`ModuleManager.DLLPred`クラスについて、引数で`factory`を指定すると`DLLEntity`オブジェクトを`self._filepath`に格納するが、`__call__`メソッドで`DLLEntity`オブジェクトと文字列を比較しており、正常に比較できていない。
```Python
class DLLPred:
def __init__(self, name=None, factory=None):
self._filepath = name or factory
def __call__(self, dll):
return self._filepath == dll.properties.getProperty("file_path")
```
またパスの区切り文字が違う場合、絶対パスと相対パスを比較する場合に、同一のだファイルやフォルダのパスにもかかわらず違うパスだと判定される。
引数で`factory`を指定した場合はプロパティから`file_path`の要素を取得して比較するように修正した。
またパスの比較に`os.path.samefile`を使用することで区切り文字の違い等があっても正常に比較できるようにした。

指定モジュールがロード済みかの判定が正常に行われていなかった問題の修正

---

OpenRTM_aist/ext/http/HTTPTransport.py
OpenRTM_aist/ext/http/__init__.py
OpenRTM_aist/ext/http/rtc.http.conf
OpenRTM_aist/ext/http/rtc.https.conf
OpenRTM_aist/ext/http/rtc.ws.conf
OpenRTM_aist/ext/http/rtc.wss.conf
setup.py

以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/999

HTTPTransportの追加

---

OpenRTM_aist/PortBase.py

以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/1022

ポート接続時の相手のポートと既に接続済みかを確認するときに、相手のポートのプロファイルを取得していた部分を修正

---

OpenRTM_aist/Manager.py

`manager.preload.modules`に指定したモジュールのロードに失敗した場合、System loggerにエラーの内容を出力するが、この時点でSystem loggerが初期化されていないためログ出力でエラーになる。
以下の`self._rtcout`はこの時点でNoneが設定されているためエラーになる。
```Python
try:
self._module.load(mpm_, basename_)
except BaseException:
self._rtcout.RTC_ERROR(OpenRTM_aist.Logger.print_exception())
```
上記のログ出力の部分をprintの標準出力に変更した。

モジュールロード失敗時のエラーメッセージ出力にSystem loggerを使わないようにする

---

OpenRTM_aist/CORBA_IORUtil.py
OpenRTM_aist/CSPInPort.py
OpenRTM_aist/ConfigAdmin.py
OpenRTM_aist/ConnectorListener.py
OpenRTM_aist/EventPort_pyfsm.py
OpenRTM_aist/ExecutionContextWorker.py
OpenRTM_aist/ExtTrigExecutionContext.py
OpenRTM_aist/FiniteStateMachineComponent.py
OpenRTM_aist/FiniteStateMachineComponentBase.py
OpenRTM_aist/GlobalFactory.py
OpenRTM_aist/InPort.py
OpenRTM_aist/InPortBase.py
OpenRTM_aist/InPortPushConnector.py
OpenRTM_aist/Manager.py
OpenRTM_aist/OutPortBase.py
OpenRTM_aist/OutPortDuplexConnector.py
OpenRTM_aist/PeriodicECSharedComposite.py
OpenRTM_aist/PeriodicExecutionContext.py
OpenRTM_aist/RTObject.py
OpenRTM_aist/RTObjectBase.py
OpenRTM_aist/__init__.py
OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py
OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceInPort.py
OpenRTM_aist/ext/transport/ROS2Transport/ROS2InPort.py
OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py

flake8の静的解析の結果、以下の警告、エラーが発生した。
```
OpenRTM_aist/CORBA_CdrMemoryStream.py:188:1: W391 blank line at end of file
OpenRTM_aist/CORBA_IORUtil.py:226:5: F405 'cdrUnmarshal' may be undefined, or defined from star imports: IORProfile_idl, omniORB
OpenRTM_aist/CORBA_IORUtil.py:237:12: F405 'cdrMarshal' may be undefined, or defined from star imports: IORProfile_idl, omniORB
OpenRTM_aist/CORBA_IORUtil.py:256:10: E231 missing whitespace after ','
OpenRTM_aist/CORBA_IORUtil.py:283:8: F405 'sys' may be undefined, or defined from star imports: IORProfile_idl, omniORB
OpenRTM_aist/CORBA_IORUtil.py:293:8: F405 'sys' may be undefined, or defined from star imports: IORProfile_idl, omniORB
OpenRTM_aist/CORBA_IORUtil.py:294:15: F405 'cdrUnmarshal' may be undefined, or defined from star imports: …
```

変数名の間違い、モジュールのimport漏れ、関数の多重定義、比較演算子の警告、エラー修正

---

OpenRTM_aist/CorbaNaming.py
OpenRTM_aist/NamingManager.py

CorbaNamingでルートコンテキストの取得失敗時(`_narrow(CosNaming.NamingContext)`)、オブジェクト取得失敗時(`self._rootContext.resolve(name_)`)等にエラーメッセージを標準出力するが、C++版と同様にこれを出力せずにNamingManagerで例外処理するように変更した。
以下の関数については動作が変わっている。
- CorbaNaming.__init__関数：ルートコンテキストがnilの場合は例外を投げる。以前はそのまま関数が終了していた。
- CorbaNaming.resolve関数：self._rootContext.resolve関数が例外を投げた場合にresolve関数内で例外処理しない。以前はresolve関数内で例外処理してNoneを返していた。
-

ネームサーバー接続失敗時、オブジェクト取得時のエラーメッセージを出力しないようにする

---

OpenRTM_aist/examples/Slider_and_Motor/slider.py

SliderコンポーネントをPython 3.10環境で実行すると、dummy_threadingの廃止とtkinterの仕様変更によりエラーになる。
- dummy_threadingをthreadingに変更した
- tkinter.DoubleVarの仕様変更に対応した

SliderコンポーネントがPython 3.10環境で実行できない問題の修正

---

OpenRTM_aist/ModuleManager.py

- モジュールロードパスに自動的に"./"が追加されるため、意図しないモジュールのロードを確認してしまう。
- RTCのモジュールのimport時にエラーが発生すると、get_loadable_modulesが途中で例外が発生してリストを取得できない
- モジュールロードパスに"./"を追加しないように修正した
- モジュールimport時に例外処理をして、エラーの場合はログに残すように修正した

モジュールロードパスにカレントディレクトリのパスが追加される問題の修正、モジュールをimportした時にエラーが発生するとget_loadable_modulesがエラーになる問題の修正

---

packages/deb/debian/changelog
packages/deb/debian/control
packages/deb/debian/copyright
packages/deb/debian/rules
packages/deb/dpkg_build.sh

close #286 
Link to #286 
- Issueに記載した修正を加えた
- 下記debパッケージの生成を確認
```
openrtm2-python3-doc_2.0.0-0_all.deb  openrtm2-python3-example_2.0.0-0_amd64.deb  
openrtm2-python3_2.0.0-0_amd64.deb
```
- マネージャー経由でのRTC起動動作確認
- この動作確認では、PythonのPR285をマージしたソースを使用
- rtc.confで下記を定義
- rtcd_python3 -d を実行し、マネージャー経由でC++とJavaの各RTCを起動できることを確認
```
manager.modules.load_path:
manager.modules.Java.load_paths: /usr/share/openrtm-2.0/components/java/RTMExamples/SimpleIO
manager.modules.C++.load_paths: /usr/share/openrtm-2.0/components/c++/examples/rtc
```

openrtm2-python3のdebパッケージ作成に関する修正

---

OpenRTM_aist/Manager.py

ロードするLoggerプラグインを絶対パスで指定した場合に、Init関数の名前が`C:/Python37/Lib/site-packages/OpenRTM_aist/ext/logger/eslogger/ESLoggerInit`のように絶対パス+Initになってロード失敗する。
Init関数の名前にパスが入らないように修正した。

Loggerプラグインを絶対パスで指定した場合にロード失敗する問題の修正

---

OpenRTM_aist/NVUtil.py

OpenRTM-aist Python版のNVUtil.appendStringValue関数で``,``区切りの文字列を生成すると、以下のように文字列の先頭にスペースが入るようになっている。
```
corba_cdr, csp_channel, data_service, direct, shared_memory
```
これがRT System Editor側で空白を削除する処理がないため、先頭のcorba_cdr以外の接続時にエラーが発生して接続できない問題が発生する。
C++版と同様にスペースが入らないように修正した。

appendStringValue関数でスペースが入らないように修正

---

OpenRTM_aist/InPort.py
OpenRTM_aist/Manager.py
OpenRTM_aist/OutPort.py
OpenRTM_aist/OutPortBase.py
OpenRTM_aist/PeriodicECSharedComposite.py
OpenRTM_aist/SdoServiceAdmin.py

- #296 
コンマ区切りの文字列を設定するプロパティについて、C++と仕様が違う部分について修正した。
以下の項目についても空白の削除をしていないが、これはC++でも削除していないため修正していない。
https://github.com/OpenRTM/OpenRTM-aist-Python/blob/f35041af5898d504855b16c3bc5d5f47a40a8ad1/OpenRTM_aist/Manager.py#L407-L408
https://github.com/OpenRTM/OpenRTM-aist-Python/blob/f35041af5898d504855b16c3bc5d5f47a40a8ad1/OpenRTM_aist/Manager.py#L2650-L2652
https://github.com/OpenRTM/OpenRTM-aist-Python/blob/f35041af5898d504855b16c3bc5d5f47a40a8ad1/OpenRTM_aist/Manager.py#L2660-L2663
https://github.com/OpenRTM/OpenRTM-aist-Python/blob/f35041af5898d504855b16c3bc5d5f47a40a8ad1/OpenRTM_aist/Manager.py#L3164
https://github.com/OpenRTM/OpenRTM-aist-Python/blob/f35041af5898d504855b16c3bc5d5f47a40a8ad1/OpenRTM_aist/Manager.py#L3206
https://github.com/OpenRTM/OpenRTM-aist-Python/blob/f35041af5898d5 …

dataport.marshaling_types、dataport.subscription_typeの文字列の修正

---

OpenRTM_aist/examples/Throughput/Throughput_py.py
OpenRTM_aist/examples/Throughput/rtc.conf

Throughputコンポーネントで設定したDataListenerが以前の仕様(ConnectorListenerStatusを返さない、ConnectorDataListenerTクラスのコールバック関数は以前は関数の中でデシリアライズをしていたが、現在はC++と同じくデシリアライズ後のオブジェクトを渡すようになっている)となっており動作しないため、現在の仕様に合わせて修正した。
またOpenRTM_aist.normalize関数の仕様が2.0.0以前と以後で違うため、該当箇所を修正した。

Throughputコンポーネントの修正

---

OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py

ConsoleInとConsoleOutを起動して、ROSTransportで接続する。
ConsoleOutをkillコマンドで終了させた後、ConsoleInでデータを送信しようとすると、ConsoleInがエラー状態になる。
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/OpenRTM_aist/DataFlowComponentBase.py", line 123, in on_execute
ret = self.onExecute(ec_id)
File "/usr/local/share/openrtm-2.0/components/python3/SimpleIO/ConsoleIn.py", line 101, in onExecute
self._outport.write()
File "/usr/local/lib/python3.8/dist-packages/OpenRTM_aist/OutPort.py", line 195, in write
ret = con.write(value)
File "/usr/local/lib/python3.8/dist-packages/OpenRTM_aist/OutPortPushConnector.py", line 283, in write
return self._publisher.write(cdr_data, -1, 0)
File "/usr/local/lib/python3.8/dist-packages/OpenRTM_aist/PublisherFlush.py", line 288, in write
self._retcode = …
```

ROSTransportでSubscriber側のRTCが異常終了すると、Publisher側のRTCがエラー状態になる問題

---

packages/deb/debian/rules
packages/deb/dpkg_build.sh
setup.cfg

close #311 
Link to #311
- これまでは　python3 -m build で生成されたwhlファイルを使ってインストールした場合、OpenRTM-aist.pthが /usr/bin下にインストールされていたが、今回の修正で、/usr/lib/python3/dist-packages下にインストールされるようになった
- debパッケージ作成処理でこの変更に対応し、合わせて setup.cfg での指定も不要なので削除した
- debパッケージを生成し、OpenRTM-aist.pthのインストール先を確認した

RTM-Python-build-idlリポジトリでの変更に対応

---

OpenRTM_aist/CorbaNaming.py
OpenRTM_aist/CorbaPort.py
OpenRTM_aist/DataFlowComponentBase.py
OpenRTM_aist/DefaultConfiguration.py
OpenRTM_aist/ECFactory.py
OpenRTM_aist/PortBase.py
OpenRTM_aist/Process.py
OpenRTM_aist/examples/AutoTest/AutoTestIn.py
OpenRTM_aist/examples/AutoTest/AutoTestOut.py
OpenRTM_aist/examples/TkJoyStick/TkJoyStickComp.py
OpenRTM_aist/ext/ssl/test/test_SSLTransport.py

Link to #319 
- 指摘されたPortBase.pyの2464行目コード部分は以下の通り
```
2463         def __init__(self, id_):
2464             """ 
2465              \param id_(string)
2466             """ 
2467             self._id = id_
```
- これはDoxygen用に \param と記述している部分で、
- Python の文字列 → \p を無効なエスケープと解釈する
- Doxygen の構文 → \param を必要としている 
- 二重バックスラッシュに変更する
```
"""
\\param id_ (string)
"""
```
- Python では \ が1つ表示されるので、Doxygen には \param として正しく認識される
- 修正は複数のDoxygenキーワードを一括置換するスクリプトを使用した。詳細は下記参照。
https://openrtm.org/redmine/projects/openrtm-aist-python/wiki/Python312環境で出るSyntaxWarning対応#複数のDoxygenキーワードを一括置換するスクリプト
- このスクリプトの実行結果は下記参照
https://openrtm.org/redmine/projects/openrtm-aist-python/wiki/Python312環境で出るSyntaxWarning対応#一括置換結果 
- 修正ソースからdebパッケージを生成し、これでインストールした環境でサンプルRTCを実行し、SyntaxWarningが出ないことを確認した（Ubuntu24.04）
- …

Python3.12環境でサンプルRTCを実行すると出るSyntaxWarning対応

---

packages/deb/debian/rules
packages/deb/dpkg_build.sh

close #321 
Link to #321 
- 今回の修正はdebパッケージ生成用定義で、OpenRTM_aist_Python と表記していてエラーになった部分だけ小文字に変更した
- whlファイルだけでなく、.dist-info ファイル名も小文字表記に変更されていたので対応した
- 修正ソースを使い、Ubuntu22.04, 24.04 それぞれの環境でdebパッケージを生成できることを確認した

debパッケージビルド時のwhlファイル名小文字表記への対応
