- PULL_REQUEST_TEMPLATE.md
Link to #2
チェックボックスをマークする方法を pull request のテンプレートに記載した.
ドキュメントの修正であるため、ビルドやテストは不要.
> [compat, document] Add the way to fill checkbox

- OpenRTM_aist/examples/Throughput/Throughput_py.py
Python3でThroughput_py.pyがエラーになる。
`async`はPython3ではコルーチン関数定義のための予約語になっている。
このため、変数名を`async_`に変更した。
Verify that the change has not introduced any regressions.
> Throughputのサンプルのバグ修正 #4

- OpenRTM_aist/examples/Throughput/Throughput_py.py
Python3でThroughput_py.pyがエラーになる。
`async`はPython3ではコルーチン関数定義のための予約語になっている。
このため、変数名を`async_`に変更した。
Verify that the change has not introduced any regressions.
> Throughputのサンプルのバグ修正(1.2) #4

- OpenRTM_aist/Singleton.py
- OpenRTM_aist/Timer.py
- OpenRTM_aist/examples/AutoTest/rtc_handle.py
- OpenRTM_aist/examples/AutoTest/rtc_handle10_11.py
close #11
Link to #11 
#11 で示した４ファイルを修正した
- Ubuntu16.04でビルド動作を確認した
> [master]Shebang has been fixed. #11

- OpenRTM_aist/Singleton.py
- OpenRTM_aist/Timer.py
- OpenRTM_aist/examples/AutoTest/rtc_handle.py
- OpenRTM_aist/examples/AutoTest/rtc_handle10_11.py
Link to #11 
#11 で示した４ファイルを修正した
- Ubuntu16.04でビルド動作を確認した
> [RELENG_1_2]Shebang has been fixed. #11

- OpenRTM_aist/examples/Slider_and_Motor/slider.py
- OpenRTM_aist/examples/TkJoyStick/tkjoystick.py
- OpenRTM_aist/examples/TkLRFViewer/TkLRFViewer.py
Link to #13 
Pull Request #19 を参照。　masterブランチに対する修正と同じ内容です。
- 修正動作をFedora29とUbuntu16.04で確認
> [RELENG_1_2]Default font of Tk has been set. #13

- MANIFEST.in
- packages/rpm/openrtm-aist_py3.spec.in
- packages/rpm/rpm_build.sh
Link to #12 
Pull Request #29 を参照。　masterブランチに対する修正と同じ内容です。
- Fedora28と29でrpmパッケージを作成して確認
> [RELENG_1_2] Shebang rewriting when creating rpm package. #12

- OpenRTM_aist/InPortCorbaCdrProvider.py
- OpenRTM_aist/InPortDSProvider.py
- OpenRTM_aist/InPortSHMProvider.py
> InPortCorbaCdrProviderのput関数で同じ処理を2回記述している問題の修正

- OpenRTM_aist/CORBA_IORUtil.py
#34 
CORBA_IORUtil.pyにreplaceEndpoint関数、toString関数を追加した。
> CORBA_IORUtilにエンドポイント置き換えのための関数を追加する

- OpenRTM_aist/ext/fsm4rtc_observer/ComponentObserverConsumer.py
- OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py
ComponentObserverのバグ修正
#41 と同じ
> ComponentObserverのバグ修正

- setup.py
setup.pyでビルド、インストールを行ってもROSTransportがインストールされない
setup.pyを修正した。
> ROSTransportをインストール対象に追加

- OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py
ROSTransportに関連する以下の問題の修正。
- トピック名に"/"を入れているが、これは別の修正で不要のため削除。
- mutexでロックする範囲が間違っていたため修正
- `return OpenRTM.BUFFER_EMPTY`と記述した部分があるが、この関数は値を返さないため修正
> ROS関連のバグ修正

- OpenRTM_aist/CorbaPort.py
- OpenRTM_aist/InPortBase.py
- OpenRTM_aist/Manager.py
- OpenRTM_aist/OutPortBase.py
トピック接続に関わる機能についてバグにより正常に動作していなかったため修正した。
動作仕様自体について誤解があり、単体テストも間違った動作仕様で作成していたため修正した。
> トピック接続機能が動作していなかったため修正

- OpenRTM_aist/Manager.py
corba.argsに以下のように設定する値にスペースが入る場合に正しくCORBAの引数が正しく設定されない。
```
corba.args: -ORBclientTransportRule "* ssl, tcp"
```
上の例で-ORBclientTransportRuleの後のスペースを削除していないことが原因だったため修正した。
> corba.argsに設定したオプションが正しく設定されない問題の修正

- OpenRTM_aist/CorbaPort.py
- OpenRTM_aist/InPortBase.py
- OpenRTM_aist/Manager.py
- OpenRTM_aist/OutPortBase.py
- OpenRTM_aist/RTObject.py
#57 
#58 
#59 
の修正をRELENG_1.2に反映
> #57 #58 #59の1.2用の修正

- OpenRTM_aist/RTObject.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/340
> 実行コンテキストに複数のRTCをアタッチしたときのRTC終了処理見直し

- OpenRTM_aist/RTM_IDL/ExtendedDataTypes.idl
- OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSSerializer.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py
ROSTransportをPython3、Windowsに対応させるための修正を行った。
まあROSTransportのシリアライザではTimedQuaternion型のデータ型の変換も定義していたが、そもそもPython版付属のIDLファイルでTimedQuaternion型が定義されていなかったので追加した。
> ROSTransportのPython3、Windows対応

- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceTopicManager.py
OpenSpliceTransportで`QosProfile`を使用していたがこれは非推奨らしいので`QosProvider`に変更した。
> OpenSpliceTransportのQosProfileをQosProviderに変更

- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceInPort.py
- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceTopicManager.py
- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceTransport.py
以下とほぼ同じ。ManagerのpreShutdownで終了処理を行うようにした。
https://github.com/OpenRTM/OpenRTM-aist/pull/369
> ManagerのpreShutdownでOpenSpliceTransportの終了処理を行う

- OpenRTM_aist/RTM_IDL/ExtendedDataTypes.idl
- OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSSerializer.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTransport.py
以下とほぼ同じ。ManagerのpreShutdownで終了処理を行うようにした。
https://github.com/OpenRTM/OpenRTM-aist/pull/369
> ManagerのpreShutdownでROSTransportの終了処理を行う

- OpenRTM_aist/ext/transport/ROS2Transport/ROS2Serializer.py
- OpenRTM_aist/ext/transport/ROS2Transport/ROS2TopicManager.py
- OpenRTM_aist/ext/transport/ROS2Transport/ROS2Transport.py
ROS2TransportのomniORBのデータ型からROS2のメッセージ型に変換する部分の不具合を修正した。
> ROS2Transportのバグ修正

- OpenRTM_aist/ext/fsm4rtc_observer/ComponentObserverConsumer.py
- OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py
C++版の以下の変更と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/408
> コンポーネントオブザーバーのタイマースレッドをonFinalizeで終了する処理に変更

- OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py
> C++版とコンポーネントオブザーバーの動作が違うため修正(1.2)

- OpenRTM_aist/RTObjectStateMachine.py
以下と同じ修正。
- https://github.com/OpenRTM/OpenRTM-aist/pull/419
> エラー遷移時にonExecuteとonStateUpdateを呼ばないようにする(1.2)

- OpenRTM_aist/RTObjectStateMachine.py
以下と同じ修正。
- https://github.com/OpenRTM/OpenRTM-aist/pull/419
> エラー遷移時にonExecuteとonStateUpdateを呼ばないようにする

- setup.py
> Linux、Python3でビルドを実行するとエラーになる問題の修正(1.2)

- OpenRTM_aist/ConnectorListener.py
- OpenRTM_aist/EventPort.py
- OpenRTM_aist/EventPort_pyfsm.py
- OpenRTM_aist/InPortDuplexConnector.py
- OpenRTM_aist/InPortPullConnector.py
- OpenRTM_aist/InPortPushConnector.py
- OpenRTM_aist/OutPortDuplexConnector.py
- OpenRTM_aist/OutPortPullConnector.py
- OpenRTM_aist/OutPortPushConnector.py
- OpenRTM_aist/examples/Serializer/ConsoleInShort.py
- OpenRTM_aist/examples/Serializer/ConsoleOutDouble.py
- OpenRTM_aist/examples/Serializer/ShortToDoubleSerializer.py
- OpenRTM_aist/examples/Serializer/rtc.conf
- OpenRTM_aist/examples/StaticFsm/Display.py
- OpenRTM_aist/examples/Throughput/Throughput_py.py
以下と同じ。
https://github.com/OpenRTM/OpenRTM-aist/pull/489
https://github.com/OpenRTM/OpenRTM-aist/pull/490
> シリアライザをInPort、OutPortで個別に設定可能にする

- OpenRTM_aist/ext/transport/ROS2Transport/ROS2Serializer.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSSerializer.py
以下と同じ。
https://github.com/OpenRTM/OpenRTM-aist/pull/491
> ROS、ROS2のシリアライザの名前変更

- OpenRTM_aist/examples/ConfigSample/ConfigSample.py
> ConfigSample.pyがPython3で正常に動作しないバグの修正

- OpenRTM_aist/ComponentActionListener.py
- OpenRTM_aist/ConfigAdmin.py
- OpenRTM_aist/ConfigurationListener.py
- OpenRTM_aist/ConnectorListener.py
- OpenRTM_aist/FsmActionListener.py
- OpenRTM_aist/InPortBase.py
- OpenRTM_aist/ListenerHolder.py
- OpenRTM_aist/Manager.py
- OpenRTM_aist/OutPortBase.py
- OpenRTM_aist/PortConnectListener.py
- OpenRTM_aist/RTObject.py
- OpenRTM_aist/RTObjectBase.py
#94 
autocleanをすべて削除。
Entryというクラスは不要になったため削除。
> autocleanを削除する

- OpenRTM_aist/ListenerHolder.py
- OpenRTM_aist/Manager.py
- OpenRTM_aist/ManagerActionListener.py
> ManagerActionListenerの基底クラス追加、引数ありListenerの修正(1.2)

- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceInPort.py
- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceOutPort.py
- OpenRTM_aist/ext/transport/ROS2Transport/ROS2InPort.py
- OpenRTM_aist/ext/transport/ROS2Transport/ROS2OutPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSMessageInfo.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSSerializer.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTransport.py
- OpenRTM_aist/ext/transport/ROSTransport/__init__.py
以下の変更を行った。
1. ノードから接続情報を取得するgetBusInfo関数の実装
2. ノード名を指定するためのパラメータ`ros.node.name`を追加
3. ROSTransport固有のパラメータには先頭に`ros.`を付けるように仕様変更。これに伴いROS2Transport、OpenSpliceも修正
4. RTCを終了してもプロセスが終了しないバグの修正
5. #97 のバグ修正
> rqt_graphでROSTransportのPublisher、Subscriberを表示するための修正、及びバグ修正

- OpenRTM_aist/ListenerHolder.py
#107 でautocleanを削除したが、修正内容に間違いがありManagerActionListenerのコールバック関数を呼ぶ際にエラーが発生するようになった。
以下のように`l`にリスナ、`f`にautoclean変数を格納するようにしているが、これはリスナ単体になったため修正した。
```Python
for (l,f) in listener.items():
```
> #107の修正にミスがあったため追加の修正

- OpenRTM_aist/RTM_IDL/ext/rtmCamera/CameraCommonInterface.idl
- OpenRTM_aist/RTM_IDL/ext/rtmManipulator/ManipulatorCommonInterface_Common.idl
- OpenRTM_aist/RTM_IDL/ext/rtmManipulator/ManipulatorCommonInterface_DataTypes.idl
- OpenRTM_aist/RTM_IDL/ext/rtmManipulator/ManipulatorCommonInterface_Middle.idl
- setup.py
C++版ではManipulatorCommonInterface、CameraCommonInterfaceのIDLファイル、ライブラリのインストールされていたが、Python版ではインストールされないため自分でIDLコンパイルを実行する必要があった。
IDLファイルの追加、setup.pyの修正を行った。
> ManipulatorCommonInterface、CameraCommonInterfaceのIDLファイル追加(1.2)

- OpenRTM_aist/ManagerConfig.py
> rtc.confのパスの修正(1.2)

- OpenRTM_aist/RTM_IDL/ext/rtmCamera/CameraCommonInterface.idl
- OpenRTM_aist/RTM_IDL/ext/rtmManipulator/ManipulatorCommonInterface_Common.idl
- OpenRTM_aist/RTM_IDL/ext/rtmManipulator/ManipulatorCommonInterface_DataTypes.idl
- OpenRTM_aist/RTM_IDL/ext/rtmManipulator/ManipulatorCommonInterface_Middle.idl
- setup.py
> ManipulatorCommonInterface、CameraCommonInterfaceのIDLファイル追加

- OpenRTM_aist/CorbaPort.py
CorbaPortのfindProviderOld関数、findProvider関数で問題がないのにログにエラーメッセージが出力される場合がある。
該当箇所を`RTC_TRACE`に変更した。
> CorbaPort.pyのログ出力の修正

- OpenRTM_aist/Manager.py
ManagerServantのCORBAオブジェクトがどこを見てもdeactivateされていない。
ただし、deactivateしていなくても現状で問題は発生していない。
念のためにManager終了時にdeactivateするようにした。
ただし、修正前後で動作に変化は見られず、単体テストの動作も修正前後のどちらも成功している。
> ManagerServantのCORBAオブジェクトをdeactivateしていない問題の修正

- OpenRTM_aist/Manager.py
- OpenRTM_aist/ManagerServant.py
- OpenRTM_aist/ext/fsm4rtc_observer/ComponentObserverConsumer.py
- OpenRTM_aist/ext/sdo/observer/COCTestRTC.py
- OpenRTM_aist/ext/sdo/observer/ComponentObserverConsumer.py
#132 の変更に漏れがあったため修正した。
- ManagerのOrbRunnerクラス、Termクラスが不要のため削除
- ComponentObserverが未修正だったため修正した
> Managerの終了処理の修正

- setup.py
`Img`をインポートするとエラーになる。
setup.pyの不備によりCameraCommonInterface、ManipulatorCommonInterfaceに関連するファイルがインストールされていなかったため修正した。
> CameraCommonInterface、ManipulatorCommonInterfaceに関連するファイルが正常にインストールされない

- setup.py
> CameraCommonInterface、ManipulatorCommonInterfaceに関連するファイルが正常にインストールされない(1.2)

- OpenRTM_aist/ExecutionContextWorker.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/653
> RTCがエラー状態から遷移しない問題の修正

- OpenRTM_aist/ExecutionContextWorker.py
> RTCがエラー状態から遷移しない問題の修正(1.2)

- OpenRTM_aist/ConnectorListener.py
#134 でコネクタリスナの仕様を変更したが、ConnectorDataListenerHolderのnotify関数で戻り値が仕様と違う部分があったため修正した。
> ConnectorDataListenerHolderのnotify関数の戻り値の間違いを修正

- OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSSerializer.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py
以下の点を修正した。
* ポート番号が9000に固定される不具合の修正
* socketのタイムアウトなどの設定がROSと違うため修正
* 大きなデータを転送できない問題の修正
* 以前はデータの先頭4byteからデータサイズを取得してそのサイズだけ受信していたが、ROSでは65536byteずつ受信しているようなので修正した。
> ROSTransportの修正

- OpenRTM_aist/version.py
version.pyに記述したOpenRTM-aistのバージョンが1.2.0になっている。
1.2.1に変更した。
> version.pyの修正(1.2)

- OpenRTM_aist/version.py
version.pyに記述したOpenRTM-aistのバージョンが1.2.0になっている。
2.0.0に変更した。
> version.pyの修正

- OpenRTM_aist/examples/StaticFsm/Inputbutton.py
- OpenRTM_aist/examples/StaticFsm/Microwave.py
- OpenRTM_aist/examples/StaticFsm/Microwave_pyfsm.py
Inputbuttonで`StringUtil.eraseBlank`関数、`StringUtil.stringTo`関数を使用しているが、#115 で仕様を変更したためエラーになる。
仕様変更後に対応するように修正した。
> StaticFsmのサンプルでStringUtilの仕様変更に対応していなかったため修正した

- OpenRTM_aist/ExecutionContextBase.py
以下と同じ。
* https://github.com/OpenRTM/OpenRTM-aist/pull/662
> ExecutionContextWorkerでオーナーのRTCが削除されない問題の修正

- OpenRTM_aist/ConnectorListener.py
ConnectorListenerHolder、ConnectorDataListenerHolderのremoveListener関数を実行すると全てのリスナが削除されるミスがあったため修正した。
> ConnectorListenerHolder、ConnectorDataListenerHolderで正常にリスナが削除されないバグの修正

- OpenRTM_aist/ExecutionContextBase.py
- OpenRTM_aist/ExecutionContextWorker.py
- OpenRTM_aist/RTObjectStateMachine.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/688
> RTCが状態遷移しない問題の修正

- OpenRTM_aist/ExecutionContextBase.py
- OpenRTM_aist/ExecutionContextWorker.py
- OpenRTM_aist/RTObjectStateMachine.py
> RTCが状態遷移しない問題の修正(1.2)

- OpenRTM_aist/ConfigAdmin.py
#115 の修正漏れによりConfigAdminのbindParameter関数内で変換用関数がFalseを返してもbindParameterがFalseを返さずに処理を続行する不具合が発生する。
変換用関数がFalseを返す場合はbindParameter関数がFalseを返すように修正した。
> ConfigAdminのbindParameter関数内のバグ修正

- OpenRTM_aist/Timer.py
Timer.pyのDelayedFunction(実行遅延関数呼び出し)が一度実行した後にTimerから削除するのが正常な動作だが削除されない。
DelayedFunctionが一度実行するとTimerから削除されるように修正した。
またコメントの一部が間違っていたため修正した。
> Timerのバグ修正、コメント修正

- OpenRTM_aist/PublisherBase.py
PublisherNew、PublisherPeriodicで別スレッドの処理を確実に終了させるために、終了処理をデストラクタからexit関数に移動してOutPortPushConnectorで呼び出すようにしたが、PublisherFlushにexit関数がないためエラーになる。
PublisherBaseでexit関数を定義したため、PublisherFlush使用時のエラーも解決した。
> PublisherBaseでexit関数を定義する

- OpenRTM_aist/CorbaNaming.py
- OpenRTM_aist/Macho.py
- OpenRTM_aist/NamingManager.py
- OpenRTM_aist/PeriodicTask.py
- OpenRTM_aist/PublisherNew.py
- OpenRTM_aist/PublisherPeriodic.py
#75
本来は変数を0ではなくNoneに設定すべき箇所を修正した。
> 0をNoneに変更する

- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceMessageInfo.py
- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceSerializer.py
- OpenRTM_aist/ext/transport/OpenSplice/OpenSpliceTopicManager.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/714
> OpenSpliceMessageInfoの仕様変更

- OpenRTM_aist/Process.py
#179 と同じ。
ただし、`svn/RELENG_1_2`ではPython2対応のために場合分けしてある。
> ローダブルモジュールの取得が失敗するエラーの修正(1.2)

- OpenRTM_aist/utils/rtcprof/rtcprof.py
> rtcprof実行時に発生するエラーの修正(1.2)

- OpenRTM_aist/ModuleManager.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/800
> ModuleManagerで複数の言語で同一の拡張子を指定した場合に発生する不具合の修正

- OpenRTM_aist/DefaultConfiguration.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/802
> DefaultConfigurationの修正

- OpenRTM_aist/ModuleManager.py
> ModuleManagerで複数の言語で同一の拡張子を指定した場合に発生する不具合の修正(1.2)

- OpenRTM_aist/DefaultConfiguration.py
> DefaultConfigurationの修正(1.2)

- OpenRTM_aist/examples/Serializer/ConsoleInShort.py
- OpenRTM_aist/examples/Serializer/ConsoleOutDouble.py
- OpenRTM_aist/examples/Serializer/ShortToDoubleSerializer.py
以下の点を修正した。
- コネクタコールバック関数の記述方法が古かったため修正
- addFactory関数の使用方法が古かったため修正
- print文を削除
> 独自シリアライザのサンプルの修正 

- OpenRTM_aist/InPortBase.py
- OpenRTM_aist/OutPortBase.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/834
> serializer_typeをmarshaling_typesに変更

- OpenRTM_aist/CORBA_CdrMemoryStream.py
- OpenRTM_aist/ConnectorListener.py
- OpenRTM_aist/InPortDuplexConnector.py
- OpenRTM_aist/InPortPullConnector.py
- OpenRTM_aist/InPortPushConnector.py
- OpenRTM_aist/OutPortDuplexConnector.py
- OpenRTM_aist/OutPortPullConnector.py
- OpenRTM_aist/OutPortPushConnector.py
- OpenRTM_aist/examples/Serializer/ShortToDoubleSerializer.py
- OpenRTM_aist/examples/Serializer/rtc.conf
シリアライザはデフォルトでCDR形式のシリアライザを使用するが、`corba`という名前は適当ではなかったため`cdr`に変更した。
> デフォルトのシリアライザの名前を変更

- OpenRTM_aist/ConnectorListener.py
- OpenRTM_aist/InPortDuplexConnector.py
- OpenRTM_aist/InPortPullConnector.py
- OpenRTM_aist/InPortPushConnector.py
- OpenRTM_aist/OutPortDuplexConnector.py
- OpenRTM_aist/OutPortPullConnector.py
- OpenRTM_aist/OutPortPushConnector.py
- OpenRTM_aist/examples/Serializer/rtc.conf
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/836
> in.marshaling_typeとout.marshaling_typeのパラメータでのシリアライザ設定機能を削除

- OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py
- 終了処理が例外の発生のため最後まで実行されない場合がある
- ROSTransportでエラーが発生したときにログに正しくエラーメッセージが出力されない場合がある。
- 例外が発生する箇所を`try`～`except`で例外処理するように変更しROS2ノードの終了処理まで実行できるようにした。
- 一部のログレベルを変更
> ROSTransportの問題修正

- OpenRTM_aist/ext/transport/ROS2Transport/ROS2InPort.py
- OpenRTM_aist/ext/transport/ROS2Transport/ROS2OutPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
ROSTransport、ROS2Transportでシリアライザの名前が一部が#90 以前の形式のままだったため修正した。
> ROSTransport、ROS2Transportのシリアライザの名前が一部間違っていたため修正

- OpenRTM_aist/InPortBase.py
- OpenRTM_aist/OutPortBase.py
- OpenRTM_aist/PortBase.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/840
> コネクタ接続時に指定のシリアライザが使用不可の場合にエラーにする

- OpenRTM_aist/ConfigAdmin.py
- OpenRTM_aist/ConnectorListener.py
- OpenRTM_aist/InPortBase.py
- OpenRTM_aist/OutPortBase.py
> 構文の間違いで発生する警告の修正

- OpenRTM_aist/utils/rtcd/__init__.py
- OpenRTM_aist/utils/rtcd/rtcd_python3
- OpenRTM_aist/utils/rtcprof/__init__.py
- OpenRTM_aist/utils/rtcprof/rtcprof_python
- OpenRTM_aist/utils/rtcprof/rtcprof_python3
> rtcd_python、rtcprof_pythonの修正

- OpenRTM_aist/Manager.py
- #217 と同じ
- masterブランチのversion.pyは2.0.0に更新済みだったので修正は不要
> Copyright message in log-header updated.

- OpenRTM_aist/ManagerServant.py
- OpenRTM_aist/ModuleManager.py
> get_loadable_modulesで取得したロード可能モジュールの言語名をrtcprofの言語に設定する(1.2)

- setup.py
Link to #224 
- document に加えるファイルの拡張子に「js」を追加した
- このソースを使って生成した doc パッケージを展開し、index.html をブラウザで開いた際、メニューリンクが表示されることを確認した
> docパッケージのドキュメントをブラウザで開いた際、メニューリンクが表示されるようにした(1.2)

- setup.py
Link to #224
- #225 と同じ
- ただし、現時点でmasterブランチソースでの deb パッケージ作成はメンテナンスしていないので、docパッケージの内容は確認できていない
> docパッケージのドキュメントをブラウザで開いた際、メニューリンクが表示されるようにした

- OpenRTM_aist/examples/component.conf
- OpenRTM_aist/examples/rtc.conf.sample
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/890
> rtc.conf.sample、component.confの修正

- OpenRTM_aist/examples/ExtTrigger/Connector.py
- OpenRTM_aist/examples/ExtTrigger/run.py
- OpenRTM_aist/examples/SimpleIO/Connector.py
- OpenRTM_aist/examples/SimpleIO/run.py
- OpenRTM_aist/examples/SimpleService/Connector.py
- OpenRTM_aist/examples/SimpleService/run.py
- OpenRTM_aist/examples/Slider_and_Motor/Connector.py
- OpenRTM_aist/examples/Slider_and_Motor/run.py
> サンプルコンポーネントのrun.pyが正常に動作するように修正(1.2)

- OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSTopicManager.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/926
> ROSTransportで複数のsubscriberにデータを送信できない問題の修正 

- OpenRTM_aist/Manager.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/951
> RTCの設定ファイルの指定する際にインスタンス名が正しく設定されていない問題の修正

- OpenRTM_aist/ext/fsm4rtc_observer/ComponentObserverConsumer.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/962
> fsm4rtc_observer/ComponentObserverConsumer.pyの記述ミスの修正

- OpenRTM_aist/ext/transport/ROSTransport/ROSInPort.py
- OpenRTM_aist/ext/transport/ROSTransport/ROSOutPort.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/992
> 環境変数ROS_MASTER_URIでros masterのアドレスを設定できるようにする

- OpenRTM_aist/ext/ssl/SSLTransport.py
- OpenRTM_aist/ext/ssl/rtc.ssl.conf
sslのエンドポイントを自動で追加する条件を変更した。
以前はgiop:ssl::のエンドポイントを無条件で追加していたが、corba.argsの-ORBendPointオプションで設定していない場合に追加するように変更した。
またconfファイル(`rtc.ssl.conf`)を追加した。
> SSLTransportの修正

- .github/workflows/analysis.yaml
- .github/workflows/static_code_analysis.yaml
- scripts/ubuntu_2004_bandit/Dockerfile
- scripts/ubuntu_2004_flake8/Dockerfile
- scripts/ubuntu_2004_pycodestyle/Dockerfile
- scripts/ubuntu_2004_pyflakes/Dockerfile
ファイルのpush、プルリクエスト作成時に静的コード解析を実行するためにワークフローファイル、Dockerfileを追加した。
以下の静的解析ツールをUbuntu 20.04環境で実行する。
- pycodestyle
- pyflakes
- flake8
- bandit
> 静的解析用のワークフローファイル、Dockerファイル追加

- OpenRTM_aist/examples/SimpleIO/Connector.py
SimpleIOのConnector.pyのおそらくコミット時に消し忘れたprint文があるため削除した。
> SimpleIOのConnector.pyのprint文を削除

- OpenRTM_aist/ModuleManager.py
- OpenRTM_aist/StringUtil.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/1037
> 言語ごとのモジュールロードパスを指定した場合にロードできないバグの修正、モジュール探索時間の短縮のための修正

- OpenRTM_aist/examples/TkLRFViewer/TkLRFViewer.py
close #266 
Link to #266 
- インデントにタブが使用されていた部分をスペースに置き換えた
- 修正したソースを使い、サンプルRTCテストスクリプトにて、TkLRFViewerテストがエラーなく実行されることを確認した
- この確認の際、テストスクリプト側もランダム数値を1/100に変更した
> サンプルRTCのTkLRFViewerのインデント修正

- OpenRTM_aist/DefaultConfiguration.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/1046
> DefaultConfiguration.hのrtcd、rtcprofコマンドの修正

- OpenRTM_aist/Manager.py
以下と同じ
- https://github.com/OpenRTM/OpenRTM-aist/pull/1052
> ログファイルに出力されるCopyright更新

- packages/deb/debian/control
Link to #289 
- Issueに記載した修正を加えた
> openrtm2-python3-docパッケージの説明を更新

- OpenRTM_aist/GlobalFactory.py
#259 でインターフェースをファクトリに追加する時に、パラメータの情報を設定する事ができるが、現状マージされていないため、addFactory関数の引数propを指定するとエラーになる。
当面の対策として、addFactory関数の引数にpropを追加して、関数の仕様を#259 と同じにした。
> addFactory関数の引数の変更

- OpenRTM_aist/Manager.py
以下と同じ。ただしPythonはデストラクタが呼ばれる保証がないため、動作は特に変化しない。
- https://github.com/OpenRTM/OpenRTM-aist/pull/1105
> Managerのshutdown時にRTCのデストラクタが呼ばれない問題の修正 

- COPYRIGHT
- OpenRTM_aist/Manager.py
> Copyright更新

- setup.cfg
Link to #308 
- Issueに記載した通りの修正を行った
- Ubuntu22.04にてdebパッケージを生成・インストールして import RTC 動作を確認
- ModuleNotFoundErrorは出なくなったことを確認
> setup.cfgで指定しているOpenRTM-aist.pthのパス修正

- OpenRTM_aist/ManagerServant.py
以下と同じ。
- https://github.com/OpenRTM/OpenRTM-aist/pull/1157
> スレーブマネージャ起動時にrtc.confを指定できるようにする

- OpenRTM_aist/version.py
- packages/deb/debian/changelog
バージョン番号を2.1.0へ更新した
- Ubuntu環境でバージョン2.1.0のwhlファイルからのdebパッケージ生成を確認
> バージョン2.1.0への更新
